### ISSUE TITLE
disk drive D no longer recognized by computer!!!!!!

### ISSUE THREAD

**Issue by misdom** [MattJaccino/spotify-downloader#13]
this would be a rare coincidence, but my external disk drive D is no longer recognized by my computer after running this in CMD.  Ive never had an issue with my computer in 10 YEARS to date. my external disk drive D is where this file downloaded to... Just a warning to others. ive restarted computer and completely cut power to everything and restarted. also unplugged external D drive and plugged back in. doesnt work. I use my D drive for games and i was gaming less than 24 hours ago from this post with no issues. this is the only file ive downloaded in over a month and havent visited any websites on this computer til now looking for a Spotify downloader. fair warning people.

**Comment by MattJaccino** [comment]
that's bizarre.  sorry you're having problems with the drive but I really don't think this tool is what caused it. did you download songs to that drive?

**Comment by MattJaccino** [comment]
only thing i can think of it's some kind of windows protection mechanism from running an unrecognized exe.  

can you confirm the drive is connected and has power when plugged in?

do you see it show up in Disk Management?

**Comment by MattJaccino** [comment]
gonna close this issue since i don't believe it's related to the tool.  please reach out and i can try to help you get back into your drive.
