### ISSUE TITLE
TROJAN

### ISSUE THREAD

**Issue by zorogoki** [MattJaccino/spotify-downloader#17]
TROJAN!!!!!!!!!!!!!!!!!!!!!!

https://www.virustotal.com/gui/file/8e8d5c70ec729340c5139821524f10c108e3df4cb9534f37531bced68445d46d?nocache=1

**Comment by jackoflanterns** [comment]
It may be marked as such because it downloads files from an external API upon user request, as this is the point of the program. However, none of the code present in the program itself is malicious, and spotifydown is generally considered safe.
