### ISSUE TITLE
Unhandled exceptions: Run without JSON, TypeError

### ISSUE THREAD

**Issue by jackoflanterns** [MattJaccino/spotify-downloader#18]
-k is a required argument in Interactive Mode, seemingly by accident:
![image](https://github.com/MattJaccino/spotify-downloader/assets/156267595/5a73ff13-f378-4a8b-ba5a-61d641811a1e)

Then, after -k is specified, the program encounters a TypeError.
![Screenshot 2024-07-03 224039](https://github.com/MattJaccino/spotify-downloader/assets/156267595/eb988f20-0a2b-4527-a72c-fcd98b00cd40)

Encountered in the **onefile** download because I was having (personal) issues running source.

**Comment by MattJaccino** [comment]
i'm not sure if the inclusion of `-k` is the issue.  Interactive mode doesn't even parse the args that are given.  The JSON errors are affecting other people too, and i'm not sure why.  the line it's complaining about is the response from the API where the songs actually get downloaded from

**Comment by MattJaccino** [comment]
patched the error from your second screenshot

**Comment by MattJaccino** [comment]
resolved in v0.2.0
