### ISSUE TITLE
Options to set retry attempts, naming format etc in .spotify_dl.cfg

### ISSUE THREAD

**Issue by Sanicle87** [MattJaccino/spotify-downloader#22]
Okay, so this isn't so much a bug report as a feature request, but I'd love it if support for the cfg file was extended. Now that we're seeing more options in interactive mode, it's starting to feel like the functionality here is lagging behind, and being able to set your own defaults would save a lot of keystrokes for each track or album downloaded.

Retries in particular would be very nice to have in interactive mode, as when downloading albums, it's quite common for at least one track to be missing and require an individual download.

That's not to take away from the work that's already been done, this is an incredibly useful tool as is.

**Comment by MattJaccino** [comment]
really good point.  will get that added

**Comment by Sanicle87** [comment]
Thankyou, I'll give that method of retries... a try. Pun actually not intended, couldn't think of a better way to phrase it.

The one other option I might make a configurable default is the bitrate, unless that's bundled into file type already. I've stuck with the original quality versions since Lucida was introduced, but it might be useful for others who want to automatically save a bit of space, eg if downloading for smaller capacity phones or the like

**Comment by MattJaccino** [comment]
check out v0.2.0beta3.  i haven't a chance to full test out the new stuff yet, so please let me know if you run into any bugs

**Comment by Sanicle87** [comment]
Thanks, but I think I'll need a little documentation to test properly.

Could I get a list of setting names (as would be entered into the config file) please? I'm guessing they're human readable, but it's difficult to guess the exact string expected for any given setting. Also, if you could give more detailed info on whether filetype/bitrate are the same setting or separate, and expected/accepted inputs for file type in particular.

In the meantime, I've noticed that the interactive prompt for server selection shows the text for file name selection in the latest beta. See attached screenshot.
![Command Prompt - spotify_dl exe 25072024 172647](https://github.com/user-attachments/assets/d1e71ef3-d4e3-4fa5-9dfe-1b00b3a44d6a)

**Comment by Sanicle87** [comment]
Okay, so I've tested using the following config (including downloading an album twice to see how it's handled)

`[Settings]
default_download_location=F:\Download\Completed\Spotify downloads\
default_downloader=lucida
default_filename_template={track_num} - {title}
default_retry_downloads_attempts=5
duplicate_download_handling=append_number
default_file_type=mp3-256`

Working great, as far as I can tell!

At the risk of being "that scope creep guy", I did think of two potential additions though. They might be more extensive changes under the hood, so I fully accept if they're going too far.

First suggestion would be the option to zero-pad track titles, so an album with more than 10 tracks would start 01, 02, 03... instead of 1, 2, 3.

Second would be the ability to include naming variables in the default download location, so that tracks can be automatically put into an artist or album subfolder.

Again though, both absolutely "nice to have", not critical.

**Comment by MattJaccino** [comment]
> Thanks, I'll have a play around.
> 
> In the meantime, I've noticed that the interactive prompt for server selection shows the text for file name selection in the latest beta. See attached screenshot. ![Command Prompt - spotify_dl exe 25072024 172647](https://private-user-images.githubusercontent.com/33881460/352213785-d1e71ef3-d4e3-4fa5-9dfe-1b00b3a44d6a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTUxMzAsIm5iZiI6MTcyMTk5NDgzMCwicGF0aCI6Ii8zMzg4MTQ2MC8zNTIyMTM3ODUtZDFlNzFlZjMtZDRlMy00ZmE1LTlkZmUtMWIwMGIzYTQ0ZDZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExNTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YzUyN2FhNDc1YWE0ODBmNzdkM2QzYWIzNWJkMjY1ZmQ2OGZjNGI1MjUxYjhjZmI4MGJiNmJlOGY3MWNiMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-odE-C4EIjmO2JgRB4AHMmRl802LryCBuS-XmmrB9C4)
> 
> (Edited to remove erroneous request for documentation: I found it in the source's readme)

lol, copy/paste got me.  fixing that

**Comment by MattJaccino** [comment]
> Okay, so I've tested using the following config (including downloading an album twice to see how it's handled)
> 
> `[Settings] default_download_location=F:\Download\Completed\Spotify downloads\ default_downloader=lucida default_filename_template={track_num} - {title} default_retry_downloads_attempts=5 duplicate_download_handling=append_number default_file_type=mp3-256`
> 
> Working great, as far as I can tell!
> 
> At the risk of being "that scope creep guy", I did think of two potential additions though. They might be more extensive changes under the hood, so I fully accept if they're going too far.
> 
> First suggestion would be the option to zero-pad track numbers, so an album with 10 or more tracks would use 01, 02, 03... instead of 1, 2, 3.
> 
> Second would be the ability to include filename variables in the default download location, so that tracks can be automatically put into an artist or album subfolder. eg C:\Spotify_Downloads\{artist}\{album}
> 
> Again though, both absolutely "nice to have", not critical.

adding docs now.

zero padding makes a lot of sense, pretty simple to implement i'd think.  the pathing based on artist can probably also be done, but it may cause problem if the track has multiple artists credited.  might create a new dir just for the collab, but will implement anyway.

**Comment by Sanicle87** [comment]
Bit of a mixed bag here, I'm afraid. 

Starting with positives, I used spotifydown as instructed, and zero padding seems to work fine.

However, there are a couple of regressions. If the path set in `default_download_location` doesn't exist, the program doesn't ask to make it, but just quits with an error. I've also noticed that albums, it now asks you to confirm the path for each individual download.

I've tried various forms of getting it to set the artist directory, but no luck so far.

`default_download_location=F:\Download\Completed\Spotify downloads\{artist}` results in the aforementioned error for a directory not existing
`
default_filename_template={artist}\{track_num} - {title}` shows the expected script output, but the files don't actually appear to download. I wasn't able to verify if this was a complete failure to download, or whether they're being saved to a different location than the one specified

**Comment by Sanicle87** [comment]
I've gone ahead and made a "default" cfg file that could be provided, to make configuration easier. If you have time, feel free to give it a look over. I've had to change the extension to .txt for github, but would obviously be .cfg in use
[spotify_dl.txt](https://github.com/user-attachments/files/16398366/spotify_dl.txt)

**Comment by MattJaccino** [comment]
> Bit of a mixed bag here, I'm afraid.
> 
> Starting with positives, I used spotifydown as instructed, and zero padding seems to work fine.
> 
> However, there are a couple of regressions. If the path set in `default_download_location` doesn't exist, the script doesn't ask to make it, but just quits with an error. I've also noticed that when downloading albums, it now asks you to confirm the path for each individual download.
> 
> I've tried various forms of getting it to set the artist directory, but no luck so far.
> 
> `default_download_location=F:\Download\Completed\Spotify downloads\{artist}` results in the aforementioned error for a directory not existing
> 
> `default_filename_template={artist}\{track_num} - {title}` shows the expected script output, but the files don't actually appear to download. I wasn't able to verify if this was a complete failure to download, or whether they're being saved to a different location than the one specified

fixing the non-existent dir bug. that was an oversight on my part when writer the parser for the .cfg.  the folder name in the filename template thing is interesting.  gonna have to play around with that to see what was going on there

**Comment by MattJaccino** [comment]
just pushed a new build under the 0.2.0b4 release

**Comment by Sanicle87** [comment]
Definite improvements, songs can now be automatically sorted into their own directories as expected.

I threw some curveballs at this one, both from Linkin Park's Reanimation album, as I remembered it having some... interesting titles.

Happy to report that "Ppr:kut (Cheapshot and Jubacca Reanimation) [feat. Rasco and Planet Asia]" downloaded fine, the colon was scrubbed as expected.

"Ntr\mssion" tripped it up though, seems slashes still aren't being scrubbed properly. Also still seeing a prompt for download location for every file in an album, whether the directory exists or not. Is it possible to revert this to being at the start of the job only, with prompts only if a directory doesn't exist (eg for multiple artists in an album)?

**Comment by MattJaccino** [comment]
no problem, thank you for helping make this tool better.  just implemented those fixes and updated the exe in the beta4 release. let me know how that works

**Comment by Sanicle87** [comment]
file name scrubbing now working well 👍 

One minor bug that's popped up between builds is that when preparing to download, the script states that it will use the built in default path (C:\Users\{username}\Downloads) and prompts to create it if it doesn't exist. Once it actually starts downloading, files do go to the directory specified in .spotify_dl.cfg, I'm guessing the check for directory is later than it should be?

Other than that, no new issues that can't be attributed to the spotifydown server. Here's hoping lucida comes back soon.

**Comment by MattJaccino** [comment]
good find on the download location preview, will get that fixed soon.  and that's a great suggestion, going to update that output with information about the retry mechanism

**Comment by Sanicle87** [comment]
Good news, I've not been able to find any new bugs! I think this ticket's ready to close, unless you find any related issues through your own testing.

**Comment by MattJaccino** [comment]
great to hear man, thank you for the suggestions and testing it all out.  if any else comes up, feel free to open a new issue

**Comment by Sanicle87** [comment]
No problem, and thanks once again for making my suggestions a reality!

If anything comes to mind I'll take you up on that offer, but for now I think you've earned a rest 😅
