### ISSUE TITLE
When retrying downloads, attempts continue up to the set limit, even if there are no more failed downloads

### ISSUE THREAD

**Issue by Sanicle87** [MattJaccino/spotify-downloader#25]
**Affected version**
0.2.0 beta5 (and probably earlier versions too)

**Expected behaviour**
On each retry attempt, spotify_dl should
1) check if the list of failed downloads is empty
2) If empty, stop. If populated, retry as long as the maximum number of retries hasn't been reached

**Actual behaviour**
if the list of failed downloads is empty, spotify_dl continues retrying with an empty list, until the maximum number of retries is reached

Fixing this would cut down on server requests and allow the script to complete as soon as all files are downloaded

**Comment by MattJaccino** [comment]
no worries about server requests since the empty list would just iterate and do nothing, but adding this to the code

EDIT: done
