### ISSUE TITLE
Artist being labeled as "Release"

### ISSUE THREAD

**Issue by swindlesmccoop** [MattJaccino/spotify-downloader#28]
Happens seemingly randomly, however the tracks that this happens on seem to be the same every single time, so if you download the same playlist twice, the same tracks will be labeled as `Release` for the artist. If there is any output or debug log I can provide, let me know. I'm using the latest compiled release.

One album that this occurs with is the [Metal Gear Rising soundtrack](https://open.spotify.com/album/3DR0FThvw6I18Ntp3D6kxf) with it looking like this:
![image](https://github.com/user-attachments/assets/7415e7d7-84f9-4e10-bc30-32fed13cb9a3)

**Comment by MattJaccino** [comment]
looking into this. Lucida appears to be down currently

**Comment by swindlesmccoop** [comment]
Is that where metadata is pulled from? I'm using the main branch that uses spotifydown.com

**Comment by MattJaccino** [comment]
Are you using Lucida (available in beta version) or Spotifydown for downloading these?  If you don't know what Lucida is, it's probably Spotifydown which can be a pretty shotty server to get tracks from.  The new version getting rolled out soon using Lucida is much more consistent

**Comment by MattJaccino** [comment]
Spotifydown < Lucida
