### ISSUE TITLE
Bug ? Or spotify patched API 

### ISSUE THREAD

**Issue by crl99** [MattJaccino/spotify-downloader#29]
Im getting error req installed.

[!] Song not found.

**Comment by MattJaccino** [comment]
please provide a screenshot of all inputs given and the URL of the song you're downloading

**Comment by MattJaccino** [comment]
If you are using Spotifydown to download songs, I recommend using the beta version of this tool and using Lucida.  It is much better

**Comment by crl99** [comment]
spotify-downloader-main\dist
![2024-08-28 01_31_15-Ragga Bomb (feat  Ragga Twins) - Skrillex   Zomboy Remix • Skrillex, Ragga Twins](https://github.com/user-attachments/assets/07d67a52-2f4f-46a3-8008-9ba8fae9c218)

**Comment by crl99** [comment]
> If you are using Spotifydown to download songs, I recommend using the beta version of this tool and using Lucida. It is much better

Im not sure if SPDWN using YT for source so i don't trust them, i wish to use this tool to get original source.

**Comment by MattJaccino** [comment]
try using the [newest release](https://github.com/MattJaccino/spotify-downloader/releases/tag/v0.2.0) which uses a new server for finding tracks.  this one actually does use the original source

**Comment by crl99** [comment]
> try using the [newest release](https://github.com/MattJaccino/spotify-downloader/releases/tag/v0.2.0) which uses a new server for finding tracks. this one actually does use the original source

I cant download anything except im going to lucida directly...hmm wird...

**Comment by crl99** [comment]
> can you send a screenshot?

Sure, also tool ask me how many attempts i want to try do dl the track i select 3 but every time failed...
![2024-08-28 01_31_15-Ragga Bomb (feat  Ragga Twins) - Skrillex   Zomboy Remix • Skrillex, Ragga Twins](https://github.com/user-attachments/assets/6d4cf046-f6a2-43f0-9710-a11d99c49eb7)

**Comment by MattJaccino** [comment]
very possible Lucida is having issues. you mind pasting the spotify link here?

and for the retries, you have to hit Enter on an empty line as if you were done before the retry mechanism kicks in

**Comment by crl99** [comment]
> very possible Lucida is having issues. you mind pasting the spotify link here?
> 
> and for the retries, you have to hit Enter on an empty line as if you were done before the retry mechanism kicks in
yea,yea i hit it, it goes 3 lines all good, but it seems that lucida has error now i try directly not working...here is another track i lost that one 
https://open.spotify.com/track/2vtwoWBK8wOq9o3grruoJw2

**Comment by groninge01** [comment]
> > very possible Lucida is having issues. you mind pasting the spotify link here?
> > and for the retries, you have to hit Enter on an empty line as if you were done before the retry mechanism kicks in
> > yea,yea i hit it, it goes 3 lines all good, but it seems that lucida has error now i try directly not working...here is another track i lost that one
> > https://open.spotify.com/track/2vtwoWBK8wOq9o3grruoJw2

The correct link is https://open.spotify.com/track/2vtwoWBK8wOq9o3grruoJw and spotifydown will d/l this track successfully so it's more to do with lucida (which appears down rn).

Tracks really not downloading by either sp or lucida have more to do with the `available_markets` of it. See for example this one: https://open.spotify.com/track/3bC96jKWLfP91MEJP1COll. The available markets are `['BS', 'GB', 'IE', 'SB', 'VC']` so I guess if the d/l servers aren't in those locations the tracks won't d/l either.

**Comment by crl99** [comment]
> > > very possible Lucida is having issues. you mind pasting the spotify link here?
> > > and for the retries, you have to hit Enter on an empty line as if you were done before the retry mechanism kicks in
> > > yea,yea i hit it, it goes 3 lines all good, but it seems that lucida has error now i try directly not working...here is another track i lost that one
> > > https://open.spotify.com/track/2vtwoWBK8wOq9o3grruoJw2
> 
> The correct link is https://open.spotify.com/track/2vtwoWBK8wOq9o3grruoJw and spotifydown will d/l this track successfully so the issue is with lucida (which appears down rn).
> 
> Tracks really not downloading by either sp or lucida have more to do with the `available_markets` of it. See for example this one: https://open.spotify.com/track/3bC96jKWLfP91MEJP1COll. The available markets are `['BS', 'GB', 'IE', 'SB', 'VC']` so I guess if the d/l servers aren't in those locations the tracks won't d/l either.

You are right for link, don't know where did i get "2" at end, but nevermind, so we are region restricted, btw lucida was down yday. i try directly couple of other songs not worked. What do you think about integrating proxy in tool ? is it possible for example EU servers, i mean this is just idea im not a programer/coder, so we can bypass region restrictions.

**Comment by groninge01** [comment]
> You are right for link, don't know where did i get "2" at end, but nevermind, so we are region restricted, btw lucida was down yday. i try directly couple of other songs not worked. What do you think about integrating proxy in tool ? is it possible for example EU servers, i mean this is just idea im not a programer/coder, so we can bypass region restrictions.

Proxying this tool won't matter. Either lucida or sp should do the proxying (lucida does some i think?).

**Comment by MattJaccino** [comment]
groninge is exactly right.  The Lucida servers are located somewhere in central Europe, so we are at the mercy of the available markets for Spotify songs.  I'm sorry about this limitation.  Glad to know Spotifydown was able to alleviate a little of this, but ultimately the region restriction is something outside of my control
