### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nk34player** [MattJaccino/spotify-downloader#30]
![image](https://github.com/user-attachments/assets/17449960-5f4e-4269-95b7-2330b4d96f3c)

**Comment by MattJaccino** [comment]
Is this using the new version?

**Comment by MattJaccino** [comment]
fixed in v0.2.1

**Comment by MattJaccino** [comment]
turns out there was a "ghost" track in the playlist that was breaking things.  more careful about looking at the tracks now

**Comment by nk34player** [comment]
even after removing it i had the same error

**Comment by MattJaccino** [comment]
no problem
