### ISSUE TITLE
Says Playlist not found or set to private but it is neither

### ISSUE THREAD

**Issue by TheDarkKnight69** [MattJaccino/spotify-downloader#6]
Like the title says, the script says Playlist not found or set to private but it is neither.

**Comment by TheDarkKnight69** [comment]
other playlists work though

**Comment by MattJaccino** [comment]
can you link me the playlist?

**Comment by TheDarkKnight69** [comment]
sure: https://open.spotify.com/playlist/1bVdMfeHGeL9JoX8Vq6zbD?si=3c208c57a4844619&pt=0980613880bb5fd8266729cf22713082

**Comment by MattJaccino** [comment]
works for me
![image](https://github.com/MattJaccino/spotify-downloader/assets/36944187/55b61463-2c83-4d25-b384-cde4aa06c110)

**Comment by MattJaccino** [comment]
bro this is a cool playlist with the video game songs.  no idea how you have elena siegman and kevin sherwood but you don't have 115 or beauty of annihilation

**Comment by TheDarkKnight69** [comment]
lol ill add them if they good :) but it literally doesnt work for me wtf

**Comment by MattJaccino** [comment]
can you send me a screenshot of what happens when you use the URL? like all of your args and output and everything like my shot
