### ISSUE TITLE
Track numbers for playlists & functionality for /Album/ links

### ISSUE THREAD

**Issue by CaffeinatedCNS** [MattJaccino/spotify-downloader#8]
Hi @MattJaccino, I'd firstly like to thank you for this project, it's great and really useful to overcome an issue I've been having.

I have a couple of suggestions/requests I'm hoping you may consider?

1. Prefixing the file names with the track number from the playlist to preserve the running order.
2. Replicating (including suggeston 1) the /Playlist/ functionality to also extend to /Album/ links.

Thanks
Liam

**Comment by MattJaccino** [comment]
hi Liam.  Caninas' PR should handle the first ask and I'm adding support for albums now.  will get everything pushed into main soon
